// This file was generated by liblab | https://liblab.com/

import { HttpClient } from '../http';
import { SdkConfig } from '../http/types';

export class BaseService {
  constructor(
    config: SdkConfig,
    public client: HttpClient = new HttpClient(config),
  ) {}

  setBaseUrl(baseUrl: string): void {
    this.client.setBaseUrl(baseUrl);
  }

  setConfig(config: SdkConfig): void {
    this.client.setConfig(config);
  }
}
