// This file was generated by liblab | https://liblab.com/

import { ZodUndefined } from 'zod';
import { HttpRequest, HttpResponse, RequestHandler } from '../types';
import { HttpError } from '../error';

export class ResponseHandler implements RequestHandler {
  next?: RequestHandler;

  async handle<T>(request: HttpRequest<T>): Promise<HttpResponse<T>> {
    const response = await this.next!.handle(request);

    if (this.isErrorResponse(response)) {
      throw new HttpError(response.metadata);
    }

    const validatedResponse = this.validateResponse(request, response);

    return validatedResponse;
  }

  private isErrorResponse(response: HttpResponse<unknown>): boolean {
    return response.metadata.status >= 400;
  }

  private async validateResponse<T>(request: HttpRequest<T>, response: HttpResponse<T>): Promise<HttpResponse<T>> {
    if (!this.hasContent(request, response)) {
      return response;
    }

    const decodedBody = new TextDecoder().decode(response.body);

    const json = JSON.parse(decodedBody);

    return {
      ...response,
      data: request.responseSchema.parse(json),
    };
  }

  private hasContent<T>(request: HttpRequest<T>, response: HttpResponse<T>): boolean {
    return (
      !!request.responseSchema && !(request.responseSchema instanceof ZodUndefined) && response.metadata.status !== 204
    );
  }
}
