// This file was generated by liblab | https://liblab.com/

import { TestSdk } from 'test-sdk';

const sdk = new TestSdk({ baseUrl: 'undefined', auth: { token: 'MY_TOKEN' } });

(async () => {
  try {
    const response = await sdk.pets.listPets();
    console.log(response);
  } catch (error) {
    console.error(error);
  }
})();
