// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { PetsService } from './services/pets';

export class TestSdk {
  constructor(
    config: SdkConfig,
    public readonly pets: PetsService = new PetsService(config),
  ) {}

  setBaseUrl(baseUrl: string): void {
    this.pets.setBaseUrl(baseUrl);
  }

  setEnvironment(environment: Environment): void {
    this.setBaseUrl(environment);
  }

  setConfig(config: SdkConfig): void {
    this.pets.setConfig(config);
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
